### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by bph** [bph/flcharity#4]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp4g\Flcharity\register_flcharity_block' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287 
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp4g_flcharity_block_init' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287

**Comment by bph** [comment]
[flcharity-0.3.5.zip](https://github.com/bph/flcharity/files/4893466/flcharity-0.3.5.zip)

**Comment by bph** [comment]
'render_callback' 	=> __NAMESPACE__ . '\render_flcharity_block'
replaced with ''render_callback' 	=> 'render_flcharity_block''

**Comment by bph** [comment]
add_action( 'plugins_loaded', __NAMESPACE__ . '\register_flcharity_block' );
replaced with: 
add_action( 'plugins_loaded', 'register_flcharity_block' );

**Comment by bph** [comment]
[flcharity-0.3.6.zip](https://github.com/bph/flcharity/files/4893490/flcharity-0.3.6.zip)

nope: same errorrs: 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'register_flcharity_block' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp4g_flcharity_block_init' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287

**Comment by bph** [comment]
So, normally the Google thing works, but this time it doesn't. This seems to be a common occurrence but none of the suggested solutions apply here.

**Comment by bph** [comment]
Went through all php files and changes the namespace to wp4g/flcharity 
[flcharity-0.3.7.zip](https://github.com/bph/flcharity/files/4893620/flcharity-0.3.7.zip)
no error messages.

**Comment by bph** [comment]
Nope, because installed the Query_monitor plugin it was hiding the warning. 
Only saw in the browser console. 
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'register_flcharity_block' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp4g_flcharity_block_init' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287

**Comment by bph** [comment]
Possible causes: 

- [ ] Space in function name.

**Comment by bph** [comment]
I got this past the Block validator, but this error message still come up. The newest Zip file. 
[flcharity-0.3.8..zip](https://github.com/bph/flcharity/files/4928148/flcharity-0.3.8.zip)

**Comment by JoshShashaty** [comment]
@bph do you need a namespace for any particular reason?

If so, try prefixing the namespace in the callback like so

`add_action( 'init', 'w4g\flcharity\w4g_flcharity_block_init' );`

OR

`add_action( 'init', __NAMESPACE__ . '\w4g_flcharity_block_init' );`  ... note the __ on either side of NAMESPACE


For `register_flcharity_block` .... I don't see a function for that callback.  But it looks like you're attempting the same thing with `register_flcharity_block` and `w4g_flcharity_block_init` ... so perhaps just delete `add_action( 'plugins_loaded', 'register_flcharity_block' );`

**Comment by bph** [comment]
That got me over the problem with the activation process. Thank you! No error messages anymore. 
But also no block in the Block editor.

**Comment by bph** [comment]
[flcharity-0.3.9.zip](https://github.com/bph/flcharity/files/4934651/flcharity-0.3.9.zip)
just a bunch of deprication notices, but that shouldn't impair the block from functioning.
