### ISSUE TITLE
Error: Uncaught (in promise) TypeError: Object (...) is not a function.

### ISSUE THREAD

**Issue by bph** [bph/flcharity#8]
Uncaught (in promise) TypeError: Object (...) is not a function. 
![Screen Shot 2020-08-23 at 5 40 13 PM](https://user-images.githubusercontent.com/39980/90989463-eaafbf80-e567-11ea-92ae-bdbf9380fcac.png)

**Comment by the-blairiest** [comment]
This error was due the following invalid javascript (in red).
![Screen Shot 2020-12-14 at 10 56 18 PM](https://user-images.githubusercontent.com/8586095/102169216-bd14bc00-3e5f-11eb-8dd0-6aa517ee1901.png)
I replaced them with the corresponding lines from the WP Block Tutorial found here:
https://developer.wordpress.org/block-editor/tutorials/create-block/block-anatomy/

**Comment by bph** [comment]
Thank yoy!

**Comment by bph** [comment]
Ah looking at it some more, I don't think that'll work. 
in the edit section. 
return <Edit {...props} should work as the edit.js was included on the top. 
but the reference might not be right because it pulls the index.js from the /build/ directory and that folder doesn't a copy of  edit.js ...

**Comment by bph** [comment]
The save section is supposed to return null because it's a dynamic block that renders the block on front end server side

https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/

**Comment by bph** [comment]
But if the index.js wouldn't call edit.js then the error message shouldn't be referencing the promise in function in the edit.js... The mystery continues :-)

**Comment by the-blairiest** [comment]
Ah, okay. I was thinking I would maybe have to add an ajax call in the save function to retrieve the current flcharity text from the database. I will finish the tutorial pages next.

**Comment by bph** [comment]
Oh and the build process puts all js files into the build/index.js file. 
I am trying some more stuff right now...

**Comment by the-blairiest** [comment]
Yes, i have run the build script myself already. It is an interesting setup.

**Comment by bph** [comment]
Ok so I fixed this particular issue 
before: 
`import {apiFetch} from  '@wordpress/api-fetch';`

Fixed: `import apiFetch from '@wordpress/api-fetch';`
